### ISSUE TITLE
Release with higher version number

### ISSUE THREAD

**Issue by orlitzky** [JBlond/mod_log_rotate#1]
Hello, first of all -- I take it this is the fixed version that works with apache-2.4?

If so, I have a favor to ask. We need to update our Gentoo package for apache-2.4 support, (see https://bugs.gentoo.org/show_bug.cgi?id=532838). We can switch to your version, but the only release on Github is tagged 1.00. Unfortunately the version we have was **also** 1.00, and we can't just silently swap them (it will cause problems with the package manager).

Would it be possible to make a release as 1.01? That way we can add the fixed version, leaving the old one where it is.

**Comment by JBlond** [comment]
Sure I do that!

**Comment by JBlond** [comment]
Just for the record. The module works out of the box for 2.4 I just added the signature.

**Comment by orlitzky** [comment]
Awesome, thank you!
