### ISSUE TITLE
Handle error.log

### ISSUE THREAD

**Issue by larsonkarl** [JBlond/mod_log_rotate#10]
Could not find a reason via Google search why the error.log is not handled by mod_log_rotate. 

Is it because error.log is typically low volume so does not grow fast enough to need rotating?

Please advise. Thanks.

**Comment by JBlond** [comment]
Please leave a comment with your relevant part of the config.

**Comment by JBlond** [comment]
@larsonkarl Some feedback would be nice

**Comment by JBlond** [comment]
I didn't read it correctly. Sorry, error log files can not be rotated with this module. The Apache process handles this differently. For the error log, you need to use rotatelogs(.exe)
