### ISSUE TITLE
Handling of the error_log

### ISSUE THREAD

**Issue by ronnybremer** [JBlond/mod_log_rotate#5]
According to Apache httpd documentation, all log output is rerouted through the mod_log_rotate handler. This does not seem to be the case for the error_log, as it will stick to the unresolved strftime string.

Maybe it should be mentioned in the readme that the error_log cannot be rotated?

**Comment by JBlond** [comment]
Yes, that is true, that the error log can not behandled.

**Comment by JBlond** [comment]
I've added that info. if you have any other idea how to improve it, just ad your idea here.
