### ISSUE TITLE
Log rotation based on day-of-month

### ISSUE THREAD

**Issue by sosherof** [JBlond/mod_log_rotate#6]
A suggested feature:  Allow rotation by day of the month.  For example, I'd like to just rotate the logs monthly on the 1st.

**Comment by JBlond** [comment]
You may start at https://github.com/JBlond/mod_log_rotate/blob/master/src/mod_log_rotate.c#L361

**Comment by sosherof** [comment]
Before I haul off and write a new option to rotate on a specific day-of-the-week and/or day-of-the-month, I also noticed that this module rotates based on the start time of the httpd service. Why not grab the create date of the file and rotate based on that? Yeah, yeah.. I'm welcome to submit a PR. LOL
