### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by JBlond** [JBlond/mod_log_rotate#8]
@SteffenAL can you please check, if the development branch still works in windows?

**Comment by SteffenAL** [comment]
In the development branch I see only a two years old  mod_log_rotate.c

Where can I find the file ?

**Comment by JBlond** [comment]
@SteffenAL That is the current file. I merged another fork into the source code.

**Comment by SteffenAL** [comment]
So I have to use the two years old file ?

**Comment by JBlond** [comment]
Yepp

**Comment by SteffenAL** [comment]
Magic is Github for me.

It builds fine and when running creates log files.

What are the changes ?

New version number ?

**Comment by JBlond** [comment]
First, it is code clean-up.
Then added some more debug and error messages.
There are two fixes included https://github.com/JBlond/mod_log_rotate/pull/7/commits/071f5ac4fc817d8967d6d8e1e77290a3093a82c9
and 
https://github.com/JBlond/mod_log_rotate/pull/7/commits/1ac6452a9776b85c1b8b5913221306e4d11f6f3f

And yes, I have to increase the version number :D

**Comment by JBlond** [comment]
@SteffenAL my tests didn't go that well

Noticed a diff with the old one.

New: When I enable the module without directives it is appending the current Unix timestamp to access.log.1568246400 (is the current date).

So it looks like that directive Rotatelogs is On by default

When I explicitly set it to Off then no timestamp is appended.

Old: Enable module without directives no timestamp is added.

I do not know what it does when you have more vhosts (tested without vhosts).

So I guess I drop those changes. Thanks for testing.
